name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'

jobs:
  dagger-ci:
    name: Dagger CI Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Run Complete CI Pipeline
      uses: dagger/dagger-for-github@v7
      with:
        version: latest
        verb: call
        args: ci --source .